default: &default
  adapter: postgresql
  encoding: unicode
  username: vagrant
  pool: 5

development:
  <<: *default
  database: obtvse_development

test:
  <<: *default
  database: obtvse_test


production:
    adapter:
    encoding: utf8
    database:
    username:
    password:
    host: localhost
