
development:
  secret_key_base: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat nibh sed nisi consequat euismod. Vivamus pulvinar sed."

test:
  secret_key_base: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat nibh sed nisi consequat euismod. Vivamus pulvinar sed."

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
